### ISSUE TITLE
Deployment failed on RedHat OpenShift on AWS

### ISSUE THREAD

**Issue by fndcz** [aws/secrets-store-csi-driver-provider-aws#130]
**Describe the bug**

**To Reproduce**

Apply the latest installer changed by #129 then the provider pod can not start and showing errors as below,

```
I0927 05:44:21.760601       1 main.go:32] Starting secrets-store-csi-driver-provider-aws version 1.0.r2-6-gee95299-2022.04.14.21.07
F0927 05:44:21.856264       1 main.go:53] Failed to listen on unix socket. error: listen unix /etc/kubernetes/secrets-store-csi-providers/aws.sock: bind: permission denied
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000124001, 0xc00015c2a0, 0xac, 0xd9)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x26ba100, 0xc000000003, 0x0, 0x0, 0xc00046c150, 0x2617629, 0x7, 0x35, 0x0)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x19b
k8s.io/klog/v2.(*loggingT).printf(0x26ba100, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1a06b42, 0x2a, 0xc0000a8020, 0x1, ...)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:751 +0x191
k8s.io/klog/v2.Fatalf(...)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1509
main.main()
	/home/ec2-user/secrets-store-csi-driver-provider-aws/main.go:53 +0x437
goroutine 34 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x26ba100)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xdf
goroutine 3 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/lib/golang/src/os/signal/signal.go:150 +0x45
goroutine 19 [chan receive]:
main.main.func1(0xc0003490e0, 0xc000210fc0)
	/home/ec2-user/secrets-store-csi-driver-provider-aws/main.go:46 +0x45
created by main.main
	/home/ec2-user/secrets-store-csi-driver-provider-aws/main.go:45 +0x31a
```
Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? **No**

If yes, the issue is likely with the k8s Secrets Store CSI driver, not the AWS provider. Open an issue in [that repo](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues).

**Expected behavior**

The pod should start as normal before the install change by PR #129

**Environment:**
OS, Go version, etc.

**Additional context**
When I rollback the change made by PR #129 everything works.

**Comment by simonmarty** [comment]
We are not able to reproduce the issue you're facing on this environment, using the commands in our README
```
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.22.13-eks-15b7512
```
```
helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
helm install -n kube-system csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver

kubectl apply -n kube-system -f https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/main/deployment/aws-provider-installer.yaml
```
Could you provide more information about your environment and the commands you ran?

**Comment by fndcz** [comment]
I'm facing the issue on ROSA (RedHat OpenShift on AWS) clusters.

versions
```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.24.0+b62823b
```
Commands used
```
oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:secrets-store-csi-driver
oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:csi-secrets-store-provider-aws
      
# Secrets Store CSI driver
helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
helm upgrade --install -n kube-system csi-secrets-store \
  --set syncSecret.enabled=true \
  --set rotationPollInterval=2m \
  --set enableSecretRotation=true \
  secrets-store-csi-driver/secrets-store-csi-driver

# Installing the AWS Provider 
kubectl apply -f https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/main/deployment/aws-provider-installer.yaml
```

**Comment by jbct** [comment]
fndcz - Thank you for providing the additional information. OpenShift is not supported by our project at this time and our recommendation would be to reach out to the OpenShift team or see if you can reproduce this on EKS clusters.
