### ISSUE TITLE
Failed to listen on unix socket. error: listen unix /etc/kubernetes/secrets-store-csi-providers/aws.sock: bind: permission denied

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [aws/secrets-store-csi-driver-provider-aws#14]
Related to #12, pods won't start on my cluster due to permissions for the hardcoded unix socket path.

```
I0521 18:18:44.622108       1 main.go:25] Starting secrets-store-csi-driver-provider-aws version 1.0.r1-2021.04.22.19.04
F0521 18:18:44.624781       1 main.go:44] Failed to listen on unix socket. error: listen unix /etc/kubernetes/secrets-store-csi-providers/aws.sock: bind: permission denied
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc000496000, 0xac, 0xce)
        /home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x25bb0e0, 0xc000000003, 0x0, 0x0, 0xc00048c150, 0x251de21, 0x7, 0x2c, 0x0)
        /home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x25bb0e0, 0x3, 0x0, 0x0, 0x195df6b, 0x2a, 0xc0003b3f18, 0x1, 0x1)
        /home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
        /home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:1463
main.main()
        /home/ec2-user/secrets-store-csi-driver-provider-aws/main.go:44 +0x2df

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x25bb0e0)
        /home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:416 +0xd8

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/golang/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/lib/golang/src/os/signal/signal.go:150 +0x45

goroutine 9 [chan receive]:
main.main.func1(0xc0003588a0, 0xc00021b180)
        /home/ec2-user/secrets-store-csi-driver-provider-aws/main.go:37 +0x45
created by main.main
        /home/ec2-user/secrets-store-csi-driver-provider-aws/main.go:36 +0x205
```

**Comment by vito-laurenza-zocdoc** [comment]
I've tried adding a PSP similar to [the one the csi driver optionally installs](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/v0.0.22/charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml), but that doesn't help either.

**Comment by vito-laurenza-zocdoc** [comment]
```diff
diff -u <(curl -sL https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/r1/deployment/aws-provider-installer.yaml) ./aws-provider-installer.yaml
--- /dev/fd/63	2021-05-21 15:33:29.000000000 -0400
+++ ./aws-provider-installer.yaml	2021-05-21 15:33:21.000000000 -0400
@@ -1,3 +1,4 @@
+# source: https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/r1/deployment/aws-provider-installer.yaml
 # https://kubernetes.io/docs/reference/access-authn-authz/rbac
 apiVersion: v1
 kind: ServiceAccount
@@ -22,6 +23,11 @@
 - apiGroups: [""]
   resources: ["nodes"]
   verbs: ["get"]
+- apiGroups: ['policy']
+  resources: ['podsecuritypolicies']
+  verbs: ['use']
+  resourceNames:
+  - csi-secrets-store-provider-aws-psp
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
@@ -36,6 +42,36 @@
   name: csi-secrets-store-provider-aws
   namespace: kube-system
 ---
+apiVersion: policy/v1beta1
+kind: PodSecurityPolicy
+metadata:
+  labels:
+    app: csi-secrets-store-provider-aws
+  name: csi-secrets-store-provider-aws-psp
+  namespace: kube-system
+spec:
+  allowPrivilegeEscalation: true
+  fsGroup:
+    ranges:
+    - max: 65535
+      min: 1
+    rule: MustRunAs
+  hostPorts:
+  - max: 65535
+    min: 0
+  privileged: true
+  runAsUser:
+    rule: RunAsAny
+  seLinux:
+    rule: RunAsAny
+  supplementalGroups:
+    ranges:
+    - max: 65535
+      min: 1
+    rule: MustRunAs
+  volumes:
+  - hostPath
+---
 apiVersion: apps/v1
 kind: DaemonSet
 metadata:
@@ -77,6 +113,7 @@
         - name: providervol
           hostPath:
             path: "/etc/kubernetes/secrets-store-csi-providers"
+            type: DirectoryOrCreate
         - name: mountpoint-dir
           hostPath:
             path: /var/lib/kubelet/pods

```

**Comment by vito-laurenza-zocdoc** [comment]
I was able to make this work (selinux was denying access to create the socket).

I think having issue #15 solved will provide a simpler way for folks to get this working in their various environments.

```diff
--- /dev/fd/63	2021-05-24 15:36:18.000000000 -0400
+++ ./aws-provider-installer.yaml	2021-05-24 15:36:16.000000000 -0400
@@ -1,3 +1,4 @@
+# source: https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/r1/deployment/aws-provider-installer.yaml
 # https://kubernetes.io/docs/reference/access-authn-authz/rbac
 apiVersion: v1
 kind: ServiceAccount
@@ -22,6 +23,11 @@
 - apiGroups: [""]
   resources: ["nodes"]
   verbs: ["get"]
+- apiGroups: ['policy']
+  resources: ['podsecuritypolicies']
+  verbs: ['use']
+  resourceNames:
+  - csi-secrets-store-provider-aws-psp
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
@@ -36,6 +42,36 @@
   name: csi-secrets-store-provider-aws
   namespace: kube-system
 ---
+apiVersion: policy/v1beta1
+kind: PodSecurityPolicy
+metadata:
+  labels:
+    app: csi-secrets-store-provider-aws
+  name: csi-secrets-store-provider-aws-psp
+  namespace: kube-system
+spec:
+  allowPrivilegeEscalation: true
+  fsGroup:
+    ranges:
+    - max: 65535
+      min: 1
+    rule: MustRunAs
+  hostPorts:
+  - max: 65535
+    min: 0
+  privileged: true
+  runAsUser:
+    rule: RunAsAny
+  seLinux:
+    rule: RunAsAny
+  supplementalGroups:
+    ranges:
+    - max: 65535
+      min: 1
+    rule: MustRunAs
+  volumes:
+  - hostPath
+---
 apiVersion: apps/v1
 kind: DaemonSet
 metadata:
@@ -54,6 +90,7 @@
       labels:
         app: csi-secrets-store-provider-aws
     spec:
+      priorityClassName: system-node-critical
       serviceAccountName: csi-secrets-store-provider-aws
       hostNetwork: true
       containers:
@@ -73,10 +110,13 @@
             - name: mountpoint-dir
               mountPath: /var/lib/kubelet/pods
               mountPropagation: HostToContainer
+          securityContext:
+            privileged: true
       volumes:
         - name: providervol
           hostPath:
             path: "/etc/kubernetes/secrets-store-csi-providers"
+            type: DirectoryOrCreate
         - name: mountpoint-dir
           hostPath:
             path: /var/lib/kubelet/pods
```

**Comment by pierluigilenoci** [comment]
@vito-laurenza-zocdoc why did you close the ticket? For me, it was still a meaningful report.
